### ISSUE TITLE
Unexpected behavior of refgenie add

### ISSUE THREAD

**Issue by jashapiro** [refgenie/refgenie#180] opened 2020-06-16 22:31 UTC
I have placed a set of index files in the directory `/refgenie/my_genome/asset1` where `/refgenie` is the root directory of my refgenie library and `my_genome` is the genome name.

I would like to add those as `my_genome/asset1`, so I ran the following command:

```
$ refgenie add my_genome/asset1 --path my_genome/asset1
Using 'default' as the default tag for 'my_genome/asset1'
Default tag for 'my_genome/asset1' set to: default
```

This seems to have the generally desired effect:

```
$ refgenie seek test/asset
/refgenie/my_genome/asset1/default/
```

However, the copying of the files from `my_genome/asset1` to `my_genome/asset1/default/` means that I now have two copies of each file, which is not exactly what I would want.

Similarly, if I want to tag assets as I add them, I might stage the files in `/refgenie/my_genome/asset1/tag1` and then run
```
$ refgenie add my_genome/asset1:tag1 --path my_genome/asset1/tag1
```

I get the most displeasing path:

```
$ refgenie seek test/asset:tag1
/refgenie/test/asset/tag1/tag1/
```

Again, the contents of `/refgenie/test/asset/tag1` are copied to `/refgenie/test/asset/tag1/tag1/` resulting in wasted space.

I tried some other schemes, thinking perhaps there was confusion where the asset id was the same as the path; things like
```
$ refgenie add my_genome/asset1:tag1 --path my_genome/incoming/asset1/tag1
```
But this resulted in
```refgenie seek my_genome/asset1:tag1
/refgenie/my_genome/incoming/tag1/tag1/
```

which is essentially the same result, with the same duplicated files.

So I suppose my question is what the intended usage and behavior of `refgenie add`?
The fact that it copies files to a tag directory seems to suggest that it might be used as an import mechanism, filing assets by the logic that refgenie prefers, but the `--path` argument requires that the files already exist in the library (or at least be specified relative to it).
However, no particular directory scheme is enforced, and the copying that happens only seems to copy the files to an immediate subdirectory with the tag name, which is quite confusing. Why not point the asset:tag id directly at the specified path?

If I am misunderstanding the intent of `refgenie add`, please do let me know. I'd be happy to discuss my use case in more depth as well. Thanks!

**Comment by nsheff** [comment] 2020-07-21 16:48
Sorry it has taken so long to respond. You are right, there is an issue here. We just haven't used `add` much, and it appears to be broken...

**Comment by stolarczyk** [comment] 2020-07-28 15:02
@jashapiro, thanks for reporting. I believe the issue is fixed now on `bugfix` branches of refgenie and refgenconf. Will keep this issue open until we make a release.

**Closed** 2020-07-29 14:55 UTC
Labels: bug, likely-solved
